// src/main/webapp/app/entities/property-serve/property-serve-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IPropertyServe } from 'app/shared/model/property-serve.model';

@Component({
    selector: 'jhi-property-serve-detail',
    templateUrl: './property-serve-detail.component.html'
})
export class PropertyServeDetailComponent implements OnInit {
    propertyServe: IPropertyServe;

    constructor(protected activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ propertyServe }) => {
            this.propertyServe = propertyServe;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="propertyServe">
            <h2><span>Property Serve</span> {{propertyServe.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span>User Id</span></dt>
                <dd>
                    <span>{{propertyServe.userId}}</span>
                </dd>
                <dt><span>Reason</span></dt>
                <dd>
                    <span>{{propertyServe.reason}}</span>
                </dd>
                <dt><span>Type</span></dt>
                <dd>
                    <span>{{propertyServe.type}}</span>
                </dd>
                <dt><span>Remark</span></dt>
                <dd>
                    <span>{{propertyServe.remark}}</span>
                </dd>
                <dt><span>Dlt</span></dt>
                <dd>
                    <span>{{propertyServe.dlt}}</span>
                </dd>
                <dt><span>Create User</span></dt>
                <dd>
                    <span>{{propertyServe.create_user}}</span>
                </dd>
                <dt><span>Create Date</span></dt>
                <dd>
                    <span>{{propertyServe.createDate}}</span>
                </dd>
                <dt><span>Update User</span></dt>
                <dd>
                    <span>{{propertyServe.update_user}}</span>
                </dd>
                <dt><span>Update Date</span></dt>
                <dd>
                    <span>{{propertyServe.update_date}}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/property-serve', propertyServe.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span> Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/property-serve/property-serve-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './property-serve.reducer';
import { IPropertyServe } from 'app/shared/model/property-serve.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPropertyServeDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class PropertyServeDetail extends React.Component<IPropertyServeDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { propertyServeEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            PropertyServe [<b>{propertyServeEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="userId">User Id</span>
            </dt>
            <dd>{propertyServeEntity.userId}</dd>
            <dt>
              <span id="reason">Reason</span>
            </dt>
            <dd>{propertyServeEntity.reason}</dd>
            <dt>
              <span id="type">Type</span>
            </dt>
            <dd>{propertyServeEntity.type}</dd>
            <dt>
              <span id="remark">Remark</span>
            </dt>
            <dd>{propertyServeEntity.remark}</dd>
            <dt>
              <span id="dlt">Dlt</span>
            </dt>
            <dd>{propertyServeEntity.dlt}</dd>
            <dt>
              <span id="create_user">Create User</span>
            </dt>
            <dd>{propertyServeEntity.create_user}</dd>
            <dt>
              <span id="createDate">Create Date</span>
            </dt>
            <dd>
              <TextFormat value={propertyServeEntity.createDate} type="date" format={APP_DATE_FORMAT} />
            </dd>
            <dt>
              <span id="update_user">Update User</span>
            </dt>
            <dd>{propertyServeEntity.update_user}</dd>
            <dt>
              <span id="update_date">Update Date</span>
            </dt>
            <dd>
              <TextFormat value={propertyServeEntity.update_date} type="date" format={APP_DATE_FORMAT} />
            </dd>
          </dl>
          <Button tag={Link} to="/entity/property-serve" replace color="info">
            <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/property-serve/${propertyServeEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ propertyServe }: IRootState) => ({
  propertyServeEntity: propertyServe.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(PropertyServeDetail);
