// src/main/webapp/app/entities/property-money/property-money-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './property-money.reducer';
import { IPropertyMoney } from 'app/shared/model/property-money.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IPropertyMoneyUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface IPropertyMoneyUpdateState {
  isNew: boolean;
}

export class PropertyMoneyUpdate extends React.Component<IPropertyMoneyUpdateProps, IPropertyMoneyUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }
  }

  saveEntity = (event, errors, values) => {
    values.createdDate = new Date(values.createdDate);
    values.lastModifiedDate = new Date(values.lastModifiedDate);

    if (errors.length === 0) {
      const { propertyMoneyEntity } = this.props;
      const entity = {
        ...propertyMoneyEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/property-money');
  };

  render() {
    const { propertyMoneyEntity, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="propertyApp.propertyMoney.home.createOrEditLabel">Create or edit a PropertyMoney</h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : propertyMoneyEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">ID</Label>
                    <AvInput id="property-money-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="addressLabel" for="address">
                    Address
                  </Label>
                  <AvField id="property-money-address" type="text" name="address" />
                </AvGroup>
                <AvGroup>
                  <Label id="shouldLabel" for="should">
                    Should
                  </Label>
                  <AvField
                    id="property-money-should"
                    type="text"
                    name="should"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' },
                      number: { value: true, errorMessage: 'This field should be a number.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="isPayLabel" check>
                    <AvInput id="property-money-isPay" type="checkbox" className="form-control" name="isPay" />
                    Is Pay
                  </Label>
                </AvGroup>
                <AvGroup>
                  <Label id="yearLabel" for="year">
                    Year
                  </Label>
                  <AvField id="property-money-year" type="text" name="year" />
                </AvGroup>
                <AvGroup>
                  <Label id="monthLabel" for="month">
                    Month
                  </Label>
                  <AvField id="property-money-month" type="text" name="month" />
                </AvGroup>
                <AvGroup>
                  <Label id="remarkLabel" for="remark">
                    Remark
                  </Label>
                  <AvField id="property-money-remark" type="text" name="remark" />
                </AvGroup>
                <AvGroup>
                  <Label id="dltLabel" for="dlt">
                    Dlt
                  </Label>
                  <AvField id="property-money-dlt" type="string" className="form-control" name="dlt" />
                </AvGroup>
                <AvGroup>
                  <Label id="createdByLabel" for="createdBy">
                    Created By
                  </Label>
                  <AvField id="property-money-createdBy" type="text" name="createdBy" />
                </AvGroup>
                <AvGroup>
                  <Label id="createdDateLabel" for="createdDate">
                    Created Date
                  </Label>
                  <AvInput
                    id="property-money-createdDate"
                    type="datetime-local"
                    className="form-control"
                    name="createdDate"
                    value={isNew ? null : convertDateTimeFromServer(this.props.propertyMoneyEntity.createdDate)}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="lastModifiedByLabel" for="lastModifiedBy">
                    Last Modified By
                  </Label>
                  <AvField id="property-money-lastModifiedBy" type="text" name="lastModifiedBy" />
                </AvGroup>
                <AvGroup>
                  <Label id="lastModifiedDateLabel" for="lastModifiedDate">
                    Last Modified Date
                  </Label>
                  <AvInput
                    id="property-money-lastModifiedDate"
                    type="datetime-local"
                    className="form-control"
                    name="lastModifiedDate"
                    value={isNew ? null : convertDateTimeFromServer(this.props.propertyMoneyEntity.lastModifiedDate)}
                  />
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/property-money" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">Back</span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp; Save
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  propertyMoneyEntity: storeState.propertyMoney.entity,
  loading: storeState.propertyMoney.loading,
  updating: storeState.propertyMoney.updating,
  updateSuccess: storeState.propertyMoney.updateSuccess
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(PropertyMoneyUpdate);

// src/main/webapp/app/entities/property-money/property-money-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import * as moment from 'moment';
import { DATE_TIME_FORMAT } from 'app/shared/constants/input.constants';
import { IPropertyMoney } from 'app/shared/model/property-money.model';
import { PropertyMoneyService } from './property-money.service';

@Component({
    selector: 'jhi-property-money-update',
    templateUrl: './property-money-update.component.html'
})
export class PropertyMoneyUpdateComponent implements OnInit {
    propertyMoney: IPropertyMoney;
    isSaving: boolean;
    createdDate: string;
    lastModifiedDate: string;

    constructor(protected propertyMoneyService: PropertyMoneyService, protected activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ propertyMoney }) => {
            this.propertyMoney = propertyMoney;
            this.createdDate = this.propertyMoney.createdDate != null ? this.propertyMoney.createdDate.format(DATE_TIME_FORMAT) : null;
            this.lastModifiedDate =
                this.propertyMoney.lastModifiedDate != null ? this.propertyMoney.lastModifiedDate.format(DATE_TIME_FORMAT) : null;
        });
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        this.propertyMoney.createdDate = this.createdDate != null ? moment(this.createdDate, DATE_TIME_FORMAT) : null;
        this.propertyMoney.lastModifiedDate = this.lastModifiedDate != null ? moment(this.lastModifiedDate, DATE_TIME_FORMAT) : null;
        if (this.propertyMoney.id !== undefined) {
            this.subscribeToSaveResponse(this.propertyMoneyService.update(this.propertyMoney));
        } else {
            this.subscribeToSaveResponse(this.propertyMoneyService.create(this.propertyMoney));
        }
    }

    protected subscribeToSaveResponse(result: Observable<HttpResponse<IPropertyMoney>>) {
        result.subscribe((res: HttpResponse<IPropertyMoney>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    protected onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    protected onSaveError() {
        this.isSaving = false;
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="jhi-property-money-heading">Create or edit a Property Money</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!propertyMoney.id">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="propertyMoney.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_address">Address</label>
                    <input type="text" class="form-control" name="address" id="field_address"
                        [(ngModel)]="propertyMoney.address" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_should">Should</label>
                    <input type="number" class="form-control" name="should" id="field_should"
                        [(ngModel)]="propertyMoney.should" required/>
                    <div [hidden]="!(editForm.controls.should?.dirty && editForm.controls.should?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.should?.errors?.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.should?.errors?.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_isPay">Is Pay</label>
                    <input type="checkbox" class="form-control" name="isPay" id="field_isPay"
                        [(ngModel)]="propertyMoney.isPay" />
                    <div [hidden]="!(editForm.controls.isPay?.dirty && editForm.controls.isPay?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.isPay?.errors?.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_year">Year</label>
                    <input type="text" class="form-control" name="year" id="field_year"
                        [(ngModel)]="propertyMoney.year" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_month">Month</label>
                    <input type="text" class="form-control" name="month" id="field_month"
                        [(ngModel)]="propertyMoney.month" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_remark">Remark</label>
                    <input type="text" class="form-control" name="remark" id="field_remark"
                        [(ngModel)]="propertyMoney.remark" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_dlt">Dlt</label>
                    <input type="number" class="form-control" name="dlt" id="field_dlt"
                        [(ngModel)]="propertyMoney.dlt" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_createdBy">Created By</label>
                    <input type="text" class="form-control" name="createdBy" id="field_createdBy"
                        [(ngModel)]="propertyMoney.createdBy" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_createdDate">Created Date</label>
                    <div class="d-flex">
                        <input id="field_createdDate" type="datetime-local" class="form-control" name="createdDate" [(ngModel)]="createdDate" placeholder="YYYY-MM-DD HH:mm"
                        />
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_lastModifiedBy">Last Modified By</label>
                    <input type="text" class="form-control" name="lastModifiedBy" id="field_lastModifiedBy"
                        [(ngModel)]="propertyMoney.lastModifiedBy" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_lastModifiedDate">Last Modified Date</label>
                    <div class="d-flex">
                        <input id="field_lastModifiedDate" type="datetime-local" class="form-control" name="lastModifiedDate" [(ngModel)]="lastModifiedDate" placeholder="YYYY-MM-DD HH:mm"
                        />
                    </div>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span>Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span>Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
