// src/main/webapp/app/entities/property-money/property-money-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './property-money.reducer';
import { IPropertyMoney } from 'app/shared/model/property-money.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPropertyMoneyDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class PropertyMoneyDetail extends React.Component<IPropertyMoneyDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { propertyMoneyEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            PropertyMoney [<b>{propertyMoneyEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="address">Address</span>
            </dt>
            <dd>{propertyMoneyEntity.address}</dd>
            <dt>
              <span id="should">Should</span>
            </dt>
            <dd>{propertyMoneyEntity.should}</dd>
            <dt>
              <span id="isPay">Is Pay</span>
            </dt>
            <dd>{propertyMoneyEntity.isPay ? 'true' : 'false'}</dd>
            <dt>
              <span id="year">Year</span>
            </dt>
            <dd>{propertyMoneyEntity.year}</dd>
            <dt>
              <span id="month">Month</span>
            </dt>
            <dd>{propertyMoneyEntity.month}</dd>
            <dt>
              <span id="remark">Remark</span>
            </dt>
            <dd>{propertyMoneyEntity.remark}</dd>
            <dt>
              <span id="dlt">Dlt</span>
            </dt>
            <dd>{propertyMoneyEntity.dlt}</dd>
            <dt>
              <span id="createdBy">Created By</span>
            </dt>
            <dd>{propertyMoneyEntity.createdBy}</dd>
            <dt>
              <span id="createdDate">Created Date</span>
            </dt>
            <dd>
              <TextFormat value={propertyMoneyEntity.createdDate} type="date" format={APP_DATE_FORMAT} />
            </dd>
            <dt>
              <span id="lastModifiedBy">Last Modified By</span>
            </dt>
            <dd>{propertyMoneyEntity.lastModifiedBy}</dd>
            <dt>
              <span id="lastModifiedDate">Last Modified Date</span>
            </dt>
            <dd>
              <TextFormat value={propertyMoneyEntity.lastModifiedDate} type="date" format={APP_DATE_FORMAT} />
            </dd>
          </dl>
          <Button tag={Link} to="/entity/property-money" replace color="info">
            <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/property-money/${propertyMoneyEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ propertyMoney }: IRootState) => ({
  propertyMoneyEntity: propertyMoney.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(PropertyMoneyDetail);

// src/main/webapp/app/entities/property-money/property-money-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IPropertyMoney } from 'app/shared/model/property-money.model';

@Component({
    selector: 'jhi-property-money-detail',
    templateUrl: './property-money-detail.component.html'
})
export class PropertyMoneyDetailComponent implements OnInit {
    propertyMoney: IPropertyMoney;

    constructor(protected activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ propertyMoney }) => {
            this.propertyMoney = propertyMoney;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="propertyMoney">
            <h2><span>Property Money</span> {{propertyMoney.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span>Address</span></dt>
                <dd>
                    <span>{{propertyMoney.address}}</span>
                </dd>
                <dt><span>Should</span></dt>
                <dd>
                    <span>{{propertyMoney.should}}</span>
                </dd>
                <dt><span>Is Pay</span></dt>
                <dd>
                    <span>{{propertyMoney.isPay}}</span>
                </dd>
                <dt><span>Year</span></dt>
                <dd>
                    <span>{{propertyMoney.year}}</span>
                </dd>
                <dt><span>Month</span></dt>
                <dd>
                    <span>{{propertyMoney.month}}</span>
                </dd>
                <dt><span>Remark</span></dt>
                <dd>
                    <span>{{propertyMoney.remark}}</span>
                </dd>
                <dt><span>Dlt</span></dt>
                <dd>
                    <span>{{propertyMoney.dlt}}</span>
                </dd>
                <dt><span>Created By</span></dt>
                <dd>
                    <span>{{propertyMoney.createdBy}}</span>
                </dd>
                <dt><span>Created Date</span></dt>
                <dd>
                    <span>{{propertyMoney.createdDate}}</span>
                </dd>
                <dt><span>Last Modified By</span></dt>
                <dd>
                    <span>{{propertyMoney.lastModifiedBy}}</span>
                </dd>
                <dt><span>Last Modified Date</span></dt>
                <dd>
                    <span>{{propertyMoney.lastModifiedDate}}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/property-money', propertyMoney.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span> Edit</span>
            </button>
        </div>
    </div>
</div>
