// src/main/webapp/app/entities/stuff/stuff-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './stuff.reducer';
import { IStuff } from 'app/shared/model/stuff.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IStuffUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface IStuffUpdateState {
  isNew: boolean;
}

export class StuffUpdate extends React.Component<IStuffUpdateProps, IStuffUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }
  }

  saveEntity = (event, errors, values) => {
    values.createDate = new Date(values.createDate);
    values.update_date = new Date(values.update_date);

    if (errors.length === 0) {
      const { stuffEntity } = this.props;
      const entity = {
        ...stuffEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/stuff');
  };

  render() {
    const { stuffEntity, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="propertyApp.stuff.home.createOrEditLabel">Create or edit a Stuff</h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : stuffEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">ID</Label>
                    <AvInput id="stuff-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="userIdLabel" for="userId">
                    User Id
                  </Label>
                  <AvField
                    id="stuff-userId"
                    type="text"
                    name="userId"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="stuffnameLabel" for="stuffname">
                    Stuffname
                  </Label>
                  <AvField
                    id="stuff-stuffname"
                    type="text"
                    name="stuffname"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="genderLabel" for="gender">
                    Gender
                  </Label>
                  <AvField id="stuff-gender" type="text" name="gender" />
                </AvGroup>
                <AvGroup>
                  <Label id="phoneLabel" for="phone">
                    Phone
                  </Label>
                  <AvField
                    id="stuff-phone"
                    type="text"
                    name="phone"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' },
                      pattern: { value: '^[0-9]{11}$', errorMessage: 'This field should follow pattern for {{ pattern }}.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="emailLabel" for="email">
                    Email
                  </Label>
                  <AvField id="stuff-email" type="text" name="email" />
                </AvGroup>
                <AvGroup>
                  <Label id="idcardLabel" for="idcard">
                    Idcard
                  </Label>
                  <AvField
                    id="stuff-idcard"
                    type="text"
                    name="idcard"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="addressLabel" for="address">
                    Address
                  </Label>
                  <AvField id="stuff-address" type="text" name="address" />
                </AvGroup>
                <AvGroup>
                  <Label id="remarkLabel" for="remark">
                    Remark
                  </Label>
                  <AvField id="stuff-remark" type="text" name="remark" />
                </AvGroup>
                <AvGroup>
                  <Label id="dltLabel" for="dlt">
                    Dlt
                  </Label>
                  <AvField id="stuff-dlt" type="string" className="form-control" name="dlt" />
                </AvGroup>
                <AvGroup>
                  <Label id="create_userLabel" for="create_user">
                    Create User
                  </Label>
                  <AvField id="stuff-create_user" type="text" name="create_user" />
                </AvGroup>
                <AvGroup>
                  <Label id="createDateLabel" for="createDate">
                    Create Date
                  </Label>
                  <AvInput
                    id="stuff-createDate"
                    type="datetime-local"
                    className="form-control"
                    name="createDate"
                    value={isNew ? null : convertDateTimeFromServer(this.props.stuffEntity.createDate)}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="update_userLabel" for="update_user">
                    Update User
                  </Label>
                  <AvField id="stuff-update_user" type="text" name="update_user" />
                </AvGroup>
                <AvGroup>
                  <Label id="update_dateLabel" for="update_date">
                    Update Date
                  </Label>
                  <AvInput
                    id="stuff-update_date"
                    type="datetime-local"
                    className="form-control"
                    name="update_date"
                    value={isNew ? null : convertDateTimeFromServer(this.props.stuffEntity.update_date)}
                  />
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/stuff" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">Back</span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp; Save
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  stuffEntity: storeState.stuff.entity,
  loading: storeState.stuff.loading,
  updating: storeState.stuff.updating,
  updateSuccess: storeState.stuff.updateSuccess
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(StuffUpdate);

// src/main/webapp/app/entities/stuff/stuff-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import * as moment from 'moment';
import { DATE_TIME_FORMAT } from 'app/shared/constants/input.constants';
import { IStuff } from 'app/shared/model/stuff.model';
import { StuffService } from './stuff.service';

@Component({
    selector: 'jhi-stuff-update',
    templateUrl: './stuff-update.component.html'
})
export class StuffUpdateComponent implements OnInit {
    stuff: IStuff;
    isSaving: boolean;
    createDate: string;
    update_date: string;

    constructor(protected stuffService: StuffService, protected activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ stuff }) => {
            this.stuff = stuff;
            this.createDate = this.stuff.createDate != null ? this.stuff.createDate.format(DATE_TIME_FORMAT) : null;
            this.update_date = this.stuff.update_date != null ? this.stuff.update_date.format(DATE_TIME_FORMAT) : null;
        });
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        this.stuff.createDate = this.createDate != null ? moment(this.createDate, DATE_TIME_FORMAT) : null;
        this.stuff.update_date = this.update_date != null ? moment(this.update_date, DATE_TIME_FORMAT) : null;
        if (this.stuff.id !== undefined) {
            this.subscribeToSaveResponse(this.stuffService.update(this.stuff));
        } else {
            this.subscribeToSaveResponse(this.stuffService.create(this.stuff));
        }
    }

    protected subscribeToSaveResponse(result: Observable<HttpResponse<IStuff>>) {
        result.subscribe((res: HttpResponse<IStuff>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    protected onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    protected onSaveError() {
        this.isSaving = false;
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="jhi-stuff-heading">Create or edit a Stuff</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!stuff.id">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="stuff.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_userId">User Id</label>
                    <input type="text" class="form-control" name="userId" id="field_userId"
                        [(ngModel)]="stuff.userId" required/>
                    <div [hidden]="!(editForm.controls.userId?.dirty && editForm.controls.userId?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.userId?.errors?.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_stuffname">Stuffname</label>
                    <input type="text" class="form-control" name="stuffname" id="field_stuffname"
                        [(ngModel)]="stuff.stuffname" required/>
                    <div [hidden]="!(editForm.controls.stuffname?.dirty && editForm.controls.stuffname?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.stuffname?.errors?.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_gender">Gender</label>
                    <input type="text" class="form-control" name="gender" id="field_gender"
                        [(ngModel)]="stuff.gender" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_phone">Phone</label>
                    <input type="text" class="form-control" name="phone" id="field_phone"
                        [(ngModel)]="stuff.phone" required pattern="^[0-9]{11}$"/>
                    <div [hidden]="!(editForm.controls.phone?.dirty && editForm.controls.phone?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.phone?.errors?.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.phone?.errors?.pattern">
                            This field should follow pattern for "Phone".
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_email">Email</label>
                    <input type="text" class="form-control" name="email" id="field_email"
                        [(ngModel)]="stuff.email" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_idcard">Idcard</label>
                    <input type="text" class="form-control" name="idcard" id="field_idcard"
                        [(ngModel)]="stuff.idcard" required/>
                    <div [hidden]="!(editForm.controls.idcard?.dirty && editForm.controls.idcard?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.idcard?.errors?.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_address">Address</label>
                    <input type="text" class="form-control" name="address" id="field_address"
                        [(ngModel)]="stuff.address" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_remark">Remark</label>
                    <input type="text" class="form-control" name="remark" id="field_remark"
                        [(ngModel)]="stuff.remark" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_dlt">Dlt</label>
                    <input type="number" class="form-control" name="dlt" id="field_dlt"
                        [(ngModel)]="stuff.dlt" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_create_user">Create User</label>
                    <input type="text" class="form-control" name="create_user" id="field_create_user"
                        [(ngModel)]="stuff.create_user" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_createDate">Create Date</label>
                    <div class="d-flex">
                        <input id="field_createDate" type="datetime-local" class="form-control" name="createDate" [(ngModel)]="createDate" placeholder="YYYY-MM-DD HH:mm"
                        />
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_update_user">Update User</label>
                    <input type="text" class="form-control" name="update_user" id="field_update_user"
                        [(ngModel)]="stuff.update_user" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_update_date">Update Date</label>
                    <div class="d-flex">
                        <input id="field_update_date" type="datetime-local" class="form-control" name="update_date" [(ngModel)]="update_date" placeholder="YYYY-MM-DD HH:mm"
                        />
                    </div>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span>Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span>Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
